-- =============================================
-- Cinema Monarca - Esquema PostgreSQL
-- Tickets Jira: KAN-9 (modelo de datos) y KAN-13 (scripts SQL)
-- Ejecutar con: npm run db:setup
-- =============================================

-- Usuarios / Auth (rol: USER = cliente, GESTOR, ADMIN)
CREATE TABLE IF NOT EXISTS usuario (
  usuario_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username         VARCHAR(80)  NOT NULL UNIQUE,
  email            VARCHAR(150) NOT NULL UNIQUE,
  password_hash    VARCHAR(255) NOT NULL,
  rol              VARCHAR(10)  NOT NULL DEFAULT 'USER'
                   CHECK (rol IN ('USER', 'GESTOR', 'ADMIN')),
  activo           BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  nombre_completo  VARCHAR(255),
  cedula           VARCHAR(20)  UNIQUE,
  telefono         VARCHAR(30),
  direccion        VARCHAR(500),
  fecha_nacimiento VARCHAR(10)
);

-- Cine y sucursales
CREATE TABLE IF NOT EXISTS cine (
  cine_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_del_cine VARCHAR(255) NOT NULL,
  cine_cont       VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS sucursal (
  bran_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bran_location VARCHAR(255),
  cine_id       BIGINT REFERENCES cine(cine_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS gestor (
  manager_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manager_details VARCHAR(500),
  sucursal_id     BIGINT REFERENCES sucursal(bran_id) ON DELETE SET NULL
);

-- Clientes
CREATE TABLE IF NOT EXISTS cliente (
  cust_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_cliente    VARCHAR(255) NOT NULL,
  cust_age          INT,
  direccion_cliente VARCHAR(500),
  numero_cliente    VARCHAR(50)
);

-- Salas (los tipos coinciden con los valores que usa el frontend)
CREATE TABLE IF NOT EXISTS sala (
  sala_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR(100) NOT NULL,
  tipo        VARCHAR(10)  NOT NULL CHECK (tipo IN ('PRO', 'TRES_D', 'DOS_D')),
  capacidad   INT NOT NULL,
  filas       INT,
  columnas    INT,
  sucursal_id BIGINT REFERENCES sucursal(bran_id) ON DELETE SET NULL
);

-- Peliculas (solo catalogo)
CREATE TABLE IF NOT EXISTS pelicula (
  movie_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR(255) NOT NULL,
  descripcion   TEXT,
  duracion_min  INT,
  genero        VARCHAR(50),
  clasificacion VARCHAR(10),
  poster_url    TEXT
);

-- Funciones: una pelicula puede tener N funciones en distintas salas y horarios
CREATE TABLE IF NOT EXISTS funcion (
  funcion_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id             BIGINT NOT NULL REFERENCES pelicula(movie_id) ON DELETE CASCADE,
  sala_id              BIGINT NOT NULL REFERENCES sala(sala_id) ON DELETE CASCADE,
  fecha                VARCHAR(20) NOT NULL,
  hora_inicio          VARCHAR(10) NOT NULL,
  precio_boleto        DOUBLE PRECISION NOT NULL DEFAULT 16000,
  capacidad_total      INT NOT NULL,
  asientos_disponibles INT NOT NULL
);

-- Reservas (apuntan a una funcion)
CREATE TABLE IF NOT EXISTS reserva (
  res_code   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     VARCHAR(255),
  tiempo     VARCHAR(50),
  fecha      VARCHAR(50),
  cont_num   VARCHAR(100),
  estado     VARCHAR(12) NOT NULL DEFAULT 'CONFIRMADA'
             CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA')),
  funcion_id BIGINT REFERENCES funcion(funcion_id) ON DELETE SET NULL,
  cust_id    BIGINT REFERENCES cliente(cust_id) ON DELETE SET NULL
);

-- Sillas: una por asiento y por funcion, con bloqueo temporal (TTL)
CREATE TABLE IF NOT EXISTS silla (
  silla_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fila          VARCHAR(2) NOT NULL,
  numero        INT NOT NULL,
  estado        VARCHAR(12) NOT NULL DEFAULT 'DISPONIBLE'
                CHECK (estado IN ('DISPONIBLE', 'OCUPADA', 'RESERVADA')),
  funcion_id    BIGINT NOT NULL REFERENCES funcion(funcion_id) ON DELETE CASCADE,
  reserva_id    BIGINT REFERENCES reserva(res_code) ON DELETE SET NULL,
  bloqueado_por VARCHAR(150),
  bloqueado_en  TIMESTAMP,
  CONSTRAINT uk_silla UNIQUE (funcion_id, fila, numero)
);

-- Transacciones / pagos (simulados)
CREATE TABLE IF NOT EXISTS transaccion (
  trans_no     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_pago    VARCHAR(20) NOT NULL
               CHECK (tipo_pago IN ('TARJETA_CREDITO', 'TARJETA_DEBITO', 'NEQUI', 'PSE')),
  pago_total   NUMERIC(10,2),
  estado_pago  VARCHAR(10) NOT NULL DEFAULT 'SIMULADO'
               CHECK (estado_pago IN ('SIMULADO', 'APROBADO', 'RECHAZADO')),
  referencia   VARCHAR(50),
  ultimos4     CHAR(4),
  fecha_inicio VARCHAR(50),
  fecha_final  VARCHAR(50),
  fecha_trans  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  cust_id      BIGINT REFERENCES cliente(cust_id) ON DELETE SET NULL,
  res_code     BIGINT REFERENCES reserva(res_code) ON DELETE SET NULL
);

-- Indices para las consultas mas frecuentes
CREATE INDEX IF NOT EXISTS idx_funcion_pelicula ON funcion(movie_id);
CREATE INDEX IF NOT EXISTS idx_funcion_sala     ON funcion(sala_id);
CREATE INDEX IF NOT EXISTS idx_silla_funcion    ON silla(funcion_id);
CREATE INDEX IF NOT EXISTS idx_reserva_cliente  ON reserva(cust_id);
CREATE INDEX IF NOT EXISTS idx_trans_cliente    ON transaccion(cust_id);
